# coding: utf-8

"""
    Phrase Strings API Reference

    The version of the OpenAPI document: 2.0.0
    Contact: support@phrase.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import phrase_api
from phrase_api.models.quality_performance_score_list_request import QualityPerformanceScoreListRequest  # noqa: E501
from phrase_api.rest import ApiException

class TestQualityPerformanceScoreListRequest(unittest.TestCase):
    """QualityPerformanceScoreListRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test QualityPerformanceScoreListRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = phrase_api.models.quality_performance_score_list_request.QualityPerformanceScoreListRequest()  # noqa: E501

        """
        if include_optional :
            return QualityPerformanceScoreListRequest(
                translation_ids = [
                    'translation_id_1'
                    ]
            )
        else :
            return QualityPerformanceScoreListRequest(
        )
        """

    def testQualityPerformanceScoreListRequest(self):
        """Test QualityPerformanceScoreListRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
