# coding: utf-8

"""
    Phrase API Reference

    The version of the OpenAPI document: 2.0.0
    Contact: support@phrase.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import phrase-api
from phrase-api.api.glossary_api import GlossaryApi  # noqa: E501
from phrase-api.rest import ApiException


class TestGlossaryApi(unittest.TestCase):
    """GlossaryApi unit test stubs"""

    def setUp(self):
        self.api = phrase-api.api.glossary_api.GlossaryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_glossaries_list(self):
        """Test case for glossaries_list

        List glossaries  # noqa: E501
        """
        pass

    def test_glossary_create(self):
        """Test case for glossary_create

        Create a glossary  # noqa: E501
        """
        pass

    def test_glossary_delete(self):
        """Test case for glossary_delete

        Delete a glossary  # noqa: E501
        """
        pass

    def test_glossary_show(self):
        """Test case for glossary_show

        Get a single glossary  # noqa: E501
        """
        pass

    def test_glossary_update(self):
        """Test case for glossary_update

        Update a glossary  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
