# coding: utf-8

"""
    Phrase Strings API Reference

    The version of the OpenAPI document: 2.0.0
    Contact: support@phrase.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import phrase_api
from phrase_api.api.automation_events_api import AutomationEventsApi  # noqa: E501
from phrase_api.rest import ApiException


class TestAutomationEventsApi(unittest.TestCase):
    """AutomationEventsApi unit test stubs"""

    def setUp(self):
        self.api = phrase_api.api.automation_events_api.AutomationEventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_account_automation_events_list(self):
        """Test case for account_automation_events_list

        List automation events for an account  # noqa: E501
        """
        pass

    def test_automation_events_list(self):
        """Test case for automation_events_list

        List events for an automation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
