# coding: utf-8

"""
    Phrase Strings API Reference

    The version of the OpenAPI document: 2.0.0
    Contact: support@phrase.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import phrase_api
from phrase_api.models.locale_download import LocaleDownload  # noqa: E501
from phrase_api.rest import ApiException

class TestLocaleDownload(unittest.TestCase):
    """LocaleDownload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test LocaleDownload
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = phrase_api.models.locale_download.LocaleDownload()  # noqa: E501

        """
        if include_optional :
            return LocaleDownload(
                id = '', 
                status = 'processing', 
                result = phrase_api.models.locale_download_result.locale_download_result(
                    url = '', ), 
                params = phrase_api.models.locale_download_params.locale_download_params(
                    file_format = '', 
                    locale_id = '', 
                    tags = '', 
                    branch = '', 
                    include_empty_translations = True, 
                    include_translated_keys = True, 
                    include_unverified_translations = True, ), 
                error = '', 
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else :
            return LocaleDownload(
        )
        """

    def testLocaleDownload(self):
        """Test LocaleDownload"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
