# coding: utf-8

"""
    Phrase Strings API Reference

    The version of the OpenAPI document: 2.0.0
    Contact: support@phrase.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from phrase_api.configuration import Configuration


class JobTemplateDetails1(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'owner': 'UserPreview',
        'creator': 'UserPreview',
        'locales': 'list[LocalePreview]'
    }

    attribute_map = {
        'owner': 'owner',
        'creator': 'creator',
        'locales': 'locales'
    }

    def __init__(self, owner=None, creator=None, locales=None, local_vars_configuration=None):  # noqa: E501
        """JobTemplateDetails1 - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._owner = None
        self._creator = None
        self._locales = None
        self.discriminator = None

        if owner is not None:
            self.owner = owner
        if creator is not None:
            self.creator = creator
        if locales is not None:
            self.locales = locales

    @property
    def owner(self):
        """Gets the owner of this JobTemplateDetails1.  # noqa: E501


        :return: The owner of this JobTemplateDetails1.  # noqa: E501
        :rtype: UserPreview
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this JobTemplateDetails1.


        :param owner: The owner of this JobTemplateDetails1.  # noqa: E501
        :type: UserPreview
        """

        self._owner = owner

    @property
    def creator(self):
        """Gets the creator of this JobTemplateDetails1.  # noqa: E501


        :return: The creator of this JobTemplateDetails1.  # noqa: E501
        :rtype: UserPreview
        """
        return self._creator

    @creator.setter
    def creator(self, creator):
        """Sets the creator of this JobTemplateDetails1.


        :param creator: The creator of this JobTemplateDetails1.  # noqa: E501
        :type: UserPreview
        """

        self._creator = creator

    @property
    def locales(self):
        """Gets the locales of this JobTemplateDetails1.  # noqa: E501


        :return: The locales of this JobTemplateDetails1.  # noqa: E501
        :rtype: list[LocalePreview]
        """
        return self._locales

    @locales.setter
    def locales(self, locales):
        """Sets the locales of this JobTemplateDetails1.


        :param locales: The locales of this JobTemplateDetails1.  # noqa: E501
        :type: list[LocalePreview]
        """

        self._locales = locales

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobTemplateDetails1):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, JobTemplateDetails1):
            return True

        return self.to_dict() != other.to_dict()
