# coding: utf-8

"""
    Phrase Strings API Reference

    The version of the OpenAPI document: 2.0.0
    Contact: support@phrase.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from phrase_api.configuration import Configuration


class OrganizationJobTemplate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'name': 'str',
        'briefing': 'str',
        'autotranslate_enabled': 'bool',
        'source_locale_id': 'str',
        'created_at': 'datetime',
        'updated_at': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'briefing': 'briefing',
        'autotranslate_enabled': 'autotranslate_enabled',
        'source_locale_id': 'source_locale_id',
        'created_at': 'created_at',
        'updated_at': 'updated_at'
    }

    def __init__(self, id=None, name=None, briefing=None, autotranslate_enabled=None, source_locale_id=None, created_at=None, updated_at=None, local_vars_configuration=None):  # noqa: E501
        """OrganizationJobTemplate - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._briefing = None
        self._autotranslate_enabled = None
        self._source_locale_id = None
        self._created_at = None
        self._updated_at = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if briefing is not None:
            self.briefing = briefing
        if autotranslate_enabled is not None:
            self.autotranslate_enabled = autotranslate_enabled
        self.source_locale_id = source_locale_id
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def id(self):
        """Gets the id of this OrganizationJobTemplate.  # noqa: E501


        :return: The id of this OrganizationJobTemplate.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OrganizationJobTemplate.


        :param id: The id of this OrganizationJobTemplate.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this OrganizationJobTemplate.  # noqa: E501


        :return: The name of this OrganizationJobTemplate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OrganizationJobTemplate.


        :param name: The name of this OrganizationJobTemplate.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def briefing(self):
        """Gets the briefing of this OrganizationJobTemplate.  # noqa: E501


        :return: The briefing of this OrganizationJobTemplate.  # noqa: E501
        :rtype: str
        """
        return self._briefing

    @briefing.setter
    def briefing(self, briefing):
        """Sets the briefing of this OrganizationJobTemplate.


        :param briefing: The briefing of this OrganizationJobTemplate.  # noqa: E501
        :type: str
        """

        self._briefing = briefing

    @property
    def autotranslate_enabled(self):
        """Gets the autotranslate_enabled of this OrganizationJobTemplate.  # noqa: E501

        When `true`, jobs created from this template are auto-translated on creation. Maps to the `autotranslate` field on the request body.   # noqa: E501

        :return: The autotranslate_enabled of this OrganizationJobTemplate.  # noqa: E501
        :rtype: bool
        """
        return self._autotranslate_enabled

    @autotranslate_enabled.setter
    def autotranslate_enabled(self, autotranslate_enabled):
        """Sets the autotranslate_enabled of this OrganizationJobTemplate.

        When `true`, jobs created from this template are auto-translated on creation. Maps to the `autotranslate` field on the request body.   # noqa: E501

        :param autotranslate_enabled: The autotranslate_enabled of this OrganizationJobTemplate.  # noqa: E501
        :type: bool
        """

        self._autotranslate_enabled = autotranslate_enabled

    @property
    def source_locale_id(self):
        """Gets the source_locale_id of this OrganizationJobTemplate.  # noqa: E501

        Optional. ID of the source locale used by jobs created from this template. When omitted, the project's default source locale is used.   # noqa: E501

        :return: The source_locale_id of this OrganizationJobTemplate.  # noqa: E501
        :rtype: str
        """
        return self._source_locale_id

    @source_locale_id.setter
    def source_locale_id(self, source_locale_id):
        """Sets the source_locale_id of this OrganizationJobTemplate.

        Optional. ID of the source locale used by jobs created from this template. When omitted, the project's default source locale is used.   # noqa: E501

        :param source_locale_id: The source_locale_id of this OrganizationJobTemplate.  # noqa: E501
        :type: str
        """

        self._source_locale_id = source_locale_id

    @property
    def created_at(self):
        """Gets the created_at of this OrganizationJobTemplate.  # noqa: E501


        :return: The created_at of this OrganizationJobTemplate.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this OrganizationJobTemplate.


        :param created_at: The created_at of this OrganizationJobTemplate.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this OrganizationJobTemplate.  # noqa: E501


        :return: The updated_at of this OrganizationJobTemplate.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this OrganizationJobTemplate.


        :param updated_at: The updated_at of this OrganizationJobTemplate.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrganizationJobTemplate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrganizationJobTemplate):
            return True

        return self.to_dict() != other.to_dict()
