# coding: utf-8

"""
    Phrase Strings API Reference

    The version of the OpenAPI document: 2.0.0
    Contact: support@phrase.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from phrase_api.configuration import Configuration


class PreTranslation(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'status': 'str',
        'translatable_type': 'str',
        'translatable_id': 'str',
        'error': 'str',
        'created_at': 'datetime',
        'updated_at': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'status': 'status',
        'translatable_type': 'translatable_type',
        'translatable_id': 'translatable_id',
        'error': 'error',
        'created_at': 'created_at',
        'updated_at': 'updated_at'
    }

    def __init__(self, id=None, status=None, translatable_type=None, translatable_id=None, error=None, created_at=None, updated_at=None, local_vars_configuration=None):  # noqa: E501
        """PreTranslation - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._status = None
        self._translatable_type = None
        self._translatable_id = None
        self._error = None
        self._created_at = None
        self._updated_at = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if status is not None:
            self.status = status
        if translatable_type is not None:
            self.translatable_type = translatable_type
        if translatable_id is not None:
            self.translatable_id = translatable_id
        self.error = error
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def id(self):
        """Gets the id of this PreTranslation.  # noqa: E501


        :return: The id of this PreTranslation.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PreTranslation.


        :param id: The id of this PreTranslation.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def status(self):
        """Gets the status of this PreTranslation.  # noqa: E501

        Current execution state of the pre-translation job. Jobs start as `pending` while queued, transition to `running` while executing, and settle to `success` or `error`.   # noqa: E501

        :return: The status of this PreTranslation.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this PreTranslation.

        Current execution state of the pre-translation job. Jobs start as `pending` while queued, transition to `running` while executing, and settle to `success` or `error`.   # noqa: E501

        :param status: The status of this PreTranslation.  # noqa: E501
        :type: str
        """
        allowed_values = ["pending", "running", "success", "error"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and status not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def translatable_type(self):
        """Gets the translatable_type of this PreTranslation.  # noqa: E501

        Resource type that was pre-translated.  # noqa: E501

        :return: The translatable_type of this PreTranslation.  # noqa: E501
        :rtype: str
        """
        return self._translatable_type

    @translatable_type.setter
    def translatable_type(self, translatable_type):
        """Sets the translatable_type of this PreTranslation.

        Resource type that was pre-translated.  # noqa: E501

        :param translatable_type: The translatable_type of this PreTranslation.  # noqa: E501
        :type: str
        """
        allowed_values = ["locale", "job", "translation_key", "upload"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and translatable_type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `translatable_type` ({0}), must be one of {1}"  # noqa: E501
                .format(translatable_type, allowed_values)
            )

        self._translatable_type = translatable_type

    @property
    def translatable_id(self):
        """Gets the translatable_id of this PreTranslation.  # noqa: E501

        ID of the targeted resource (locale ID, job ID, key ID, or upload ID).  # noqa: E501

        :return: The translatable_id of this PreTranslation.  # noqa: E501
        :rtype: str
        """
        return self._translatable_id

    @translatable_id.setter
    def translatable_id(self, translatable_id):
        """Sets the translatable_id of this PreTranslation.

        ID of the targeted resource (locale ID, job ID, key ID, or upload ID).  # noqa: E501

        :param translatable_id: The translatable_id of this PreTranslation.  # noqa: E501
        :type: str
        """

        self._translatable_id = translatable_id

    @property
    def error(self):
        """Gets the error of this PreTranslation.  # noqa: E501

        Error message. `null` unless the job's status is `error`.  # noqa: E501

        :return: The error of this PreTranslation.  # noqa: E501
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this PreTranslation.

        Error message. `null` unless the job's status is `error`.  # noqa: E501

        :param error: The error of this PreTranslation.  # noqa: E501
        :type: str
        """

        self._error = error

    @property
    def created_at(self):
        """Gets the created_at of this PreTranslation.  # noqa: E501


        :return: The created_at of this PreTranslation.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this PreTranslation.


        :param created_at: The created_at of this PreTranslation.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this PreTranslation.  # noqa: E501


        :return: The updated_at of this PreTranslation.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this PreTranslation.


        :param updated_at: The updated_at of this PreTranslation.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PreTranslation):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PreTranslation):
            return True

        return self.to_dict() != other.to_dict()
